name: booking_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.26.0
