name: "Flutter Web App Deployment"

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.cicd.outputs.page-url }}
    steps:
      - uses: g1j0shi/flutter-web-app-deployment@main
        id: cicd
        with:
          working-directory: "./apps/frontend"
          build-target: "./lib/main_production.dart"
